version: '3.9'
services: 
app: 
container_name: Quize-app-testing
build: 
restart: always 

#Specify a .env file for credentials 
#The AWS_INSTANCE_URL envrionment variablepreprended to that file 
#env_file: .env 

volumes: 
  - ,:/app 
  - /app/node_modules 

ports: 
- 3000:3000 
